### ISSUE TITLE
Problems with SW - bouncing maybe?

### ISSUE THREAD

**Issue by doug-doug** [Ax-LED/MMM-Navigate#3]
So I am set up as described in the ReadMe but I am having problems when depressing the rotary - nothing happens.  The rotation works okay but if I turn too too fast, it seems to get a bit confused.  I note the remark about a capacitor to control bouncing - is this my problem with the SW?  if so, what value cap should I use?

**Comment by Ax-LED** [comment]
@doug-doug 
Which of the 3 functions doesnt work as expected? Turn right, turn left or press?
I know two was to correct bouncing:
**1. by software, see node_helper.js (debounceTimeout : 50):**
```
const A = new Gpio(self.config.GPIOPins[0], 'in', 'both',{debounceTimeout : 50 }); //BCM Pin 26
const B = new Gpio(self.config.GPIOPins[1], 'in', 'both',{debounceTimeout : 50 }); //BCM Pin 20
const C = new Gpio(self.config.GPIOPins[2], 'in', 'both',{debounceTimeout : 20 }); //BCM Pin 19
```
and try what fit best to your rotary encoder and behavior of using it.
**2. by capacitors:** 
I installed some for testing purposes and it feels a bit better know. Make sure to place them close to the GPIO Pins for best effect.
AxLED

**Comment by doug-doug** [comment]
I did adjust the timeout for the turns to 25 and that seemed to improve the responsiveness there.  Thanks.

The one not working at all is the "press" (pin 19).  Just cannot figure out why press does not work.  I tried setting timeout at 5, 20, 50, 150, 500 - no change.

How can I tell if a capacitor will help, and if I use one, what value should I try?

**Comment by Ax-LED** [comment]
I use 100nF ceramik capacitors. But back to you problem, even with no capacitor the **"press"** should work (maybe it bounces but it should work somehow).

- Are you sure you use PIN19 (BCM numbering)? 
- Can you post the code of MMM-Navigate from your config.js file?

AxLED

**Comment by doug-doug** [comment]
positive on pin 19.

my code is as follows:

==============================================
		,{
			module: "MMM-Navigate"
			,header: "Navigation"
			,position: "top_left"
			,config: {
				Alias: [
					'Test notification'
					,'Restart MagicMirror (PM2)'
					,'Restart'
					,'Shutdown'
				]
				,Action: [
					// ======== single action, execute on press ========
					// - - - - 'Test notification' - - - -
					 {notification: "SHOW_ALERT", payload: {type:"notification",message:"This is a test..."}}
					// - - - - 'Restart MagicMirror (PM2)' - - - -
					,{notification: "REMOTE_ACTION", payload: {action: "RESTART"}}
					// - - - - 'Restart' - - - -
					,{notification: "REMOTE_ACTION", payload: {action: "REBOOT"}}
					// - - - - 'Shutdown' - - - -
					,{notification: "REMOTE_ACTION", payload: {action: "SHUTDOWN"}}
				]
				// - - rotary cw, rotary ccw, rotary press - -
				,GPIOPins: [26,20,19] //  (BCM Numbering)
			}
		}
==============================================
notification  module works in its own right but not if triggered by a push.


also, I note that the options do not fade out after a period of time as supposed to.  I archived my config file and deleted my MM so I could do a clean install - no change.  rotary works, no push option.

**Comment by doug-doug** [comment]
sorry hit wrong button - still a noob....

**Comment by doug-doug** [comment]
current code, still having an issue...
...
		,{
			module: "MMM-Navigate"
			,header: "Navigation"
			,position: "top_left"
			,config: {
				Alias: [
					'Test Notification'
					,'Test Notification #2'
				]
				,Action: [
					{notification: "SHOW_ALERT", payload: {type:"notification", message:"This is a test..."}}
					,{notification: "SHOW_ALERT", payload: {type:"notification", message:"This is an alternate test..."}}
				]
				,GPIOPins: [26,20,19]
			}
		}
...

**Comment by doug-doug** [comment]
alert module is placed before the navigation module and works okay.

**Comment by Ax-LED** [comment]
@doug-doug 
Do you have the module [https://github.com/Jopyth/MMM-Remote-Control](https://github.com/Jopyth/MMM-Remote-Control) installed? Because your config with ... SHOW_ALERT will be processed by MMM-Remote-Control and if this module is missing there will be now notification show up.

AxLED

**Comment by doug-doug** [comment]
REMOTE-CONTROL is installed.  I can interface with the MM by my iPhone and trigger a restart from there as well as send alerts.  If the problem is through R-C then what can I do to troubleshoot it?

**Comment by Ax-LED** [comment]
@doug-doug 
I dont know why it not works in your environment, I did an update today, maybe this helps.
AxLED

**Comment by doug-doug** [comment]
so i have been trying different things since your update and I discovered i have a package-lock.json file in the folder.  some told me this might mean I have a problem. Does it?

**Comment by doug-doug** [comment]
Another thought: I installed remote control’s main branch, not the developer branch if that info is useful

**Comment by Ax-LED** [comment]
@doug-doug 
I dont really know what the source of the problem is, maybe you can give me some answers to my questions and i try to reproduce it (if my equipment is equivalent).
**Type of rotary encoder:**
**Hardware you are running MagicMirror on:**
**Version of MagicMirror:**
**Installed Modules:**
**What exactly does not work:** 
If i unterstood you correct, only the push function doesnt work? Left and right turn of rotary are working? Please commit or commend.

Thanks in advance.

AxLED

**Comment by doug-doug** [comment]
The rotary encoder comes from an adruino sensor kit I got on Amazon (https://www.amazon.com/gp/product/B016D5L5KE/ref=oh_aui_detailpage_o03_s01?ie=UTF8&psc=1).

The hardware is a Rapberry Pi 3.

MM version is the latest version (did run "npm i -g npm").  In trouble shooting I have done a clean install of Raspian, with a clean install of MM and the Remote Control.  I have tried the main branch but currently have the developer branch installed.

Installed modules from top down:
1. MMM-Remote-Control
2. MMM-Navigate
3. alert (deafult module)
4. updatenotification (default module)
5. worldclock
6. MMM-ip
7. MMM-connection-status
8. MMM-DHT-Sensor
9. MMM-AirQuality
9. currentweather (default module)
10. weatherforecast (default module)

The configuration of MMM-Navigate has four choices:
Test notification, Restart MM, Restart (Pi), and Shutdown (Pi)

The turn function works.  The Navigate pane never fades away.  If I click on the rotary, nothing happens but electrically, the voltage of GPIO does change.  If I tap the option (I have a touch screen installed) all four of the options will only restart MM.

Assuming my rotary is good (using a volt meter, it behaves as expected).  The other variable here is Remote-Control and that seems to work okay.

**Comment by Ax-LED** [comment]
@doug-doug 
Hi DougDoug,

i tried to reproduce your error.
**I am using following setup:**

- Hardware: Raspberry Pi2 Modell B
- MM 2.5.0

**Modules:**
All that you are listed, i only have one question to
MMM-DTH-Sensor (there are two repos, i took https://github.com/bernardpletikosa/MMM-DHT-Sensor, please confirm if this is the right one).
I can not use the DHT-Sensor because i dont have this sensor.

Touch on MMM-Navigate doesnt work, as my modules doesnt react on touch.
MMM-Navigate can also be controlled by browser, can you please try following links?
http://yourmmip:8080/remote?action=NOTIFICATION&notification=CCW emulates turning rotary counterclockwise 
http://yourmmip:8080/remote?action=NOTIFICATION&notification=CW emulates turning rotary clockwise 
http://yourmmip:8080/remote?action=NOTIFICATION&notification=PRESSED emulates pressing rotary encoder

So we can find out if its the rotary hardware or the software/modules on your pi.
If you get an "empty" notification box, thats also ok, i found a css error in MM 2.5.0

Do you have PM2 installed and configured? Otherwise "Restart" and "Shutdown" wont work properly.

AxLED

**Comment by doug-doug** [comment]
I dropped the DHT-Sensor so I can match you.  While this did not change my problem I was able to get the behaviors you described above by sending the commands.  So sending the codes to the software makes it work as expected.  I was even able to reboot and to shutdown.  I did get a blank message box as well.  Once a PRESS was recognized, the Navigate panel did fade out, something it would not do before.  It returns when I turn the rotary and/or send the rotate commands.

I have verified that the switch's SW pin is connected to GPIO 19 (pin 33).  I have tried this on two separate Pis (twins of each other, hardware-wise).  While I am sure the rotary is okay electrically, the only logical conclusion is that it must not be.  Can you recommend a good replacement?  Can you link to something on Amazon that has the preferred rotary so I can pick that up?  Since mine is a generic from a kit, it must not be the right one or I need to buffer it with resistors/capacitors.

**Comment by Ax-LED** [comment]
@doug-doug 

sounds good, we are moving forward. 
**1. blank message box:**
This looks like an error in one line of code of ...modules\default\alert\alert.js (at M; 2.5.0)
If you change line 47 from
`msg += "<span class='light bright small'>" + message.message + "</span>";`
to
`msg += "<span class='light dimmed small'>" + message.message + "</span>";`
you should be able to read the text. 
**Explanation:** the messagebox has the same color as the text, so the message box seems to be blank.

**2. Rotary Encoder, Switch function**
I think there is an error in your connection, BCM19 ist Pin 35 (not Pin 33 as you wrote). See BCM Pinout pictures in the web. If the cable for the switch function is on the wrong pin, the module cant receive this signal. Please check again.

**3. Supply source for rotary encoder:**
I bought 2 of them and both work:
[Amazon KY-040 Rotary Encoder](https://www.amazon.de/gp/product/B013UTHNYI/ref=oh_aui_detailpage_o09_s00?ie=UTF8&psc=1)

AxLED

**Comment by doug-doug** [comment]
I stand corrected on the pin number but I confirm that I am plugged into GPIO 19 - third from end.
I will be getting a new rotary and am closing this issue for now.  I will revisit it once the new one arrives.
Thank you!

**Comment by doug-doug** [comment]
issue closed - problem seems to be incompatible/incorrect hardware.
