### ISSUE TITLE
run another module

### ISSUE THREAD

**Issue by erkilic** [Ax-LED/MMM-Navigate#7]
Hi,
first of all thx for this very useful module. 
I hope you can help me with a small issue.
Your programm is working well (rotary encoder rotation and press function of your examples are working)
but how can I call my own function which is written in my own node_helper.js

e.g. in my node_helper.js:
socketNotificationReceived: function(notification, payload) 	{
	if (notification === "PLAY_IT") { let filename=payload.occasion; ......

then I though I only have to write in the config file in the Action section:
...
 {notification: 'PLAY_IT', payload: {occasion: "sample_text"}}, 
....
but it doesn't work? My function will never called. So how can I tell your programm that it has to run the function in my node_helper.js?

Hope you can help me soon.

Thx in dvance
Gürkan

**Comment by Ax-LED** [comment]
@erkilic,

can you tell me a link to your code on github?
From MMM-Navigate it is not possible to send instructions to your node_helper.js.
But you can complete the code of your main.js with code like [https://github.com/Ax-LED/MMM-Navigate/blob/master/MMM-Navigate.js#L151](https://github.com/Ax-LED/MMM-Navigate/blob/master/MMM-Navigate.js#L151).

Regards

AxLED

**Comment by erkilic** [comment]
Ok thx AxLED. I will try to implement it.

Gürkan

 

 

Von: Ax-LED <notifications@github.com> 
Gesendet: Freitag, 8. Januar 2021 19:43
An: Ax-LED/MMM-Navigate <MMM-Navigate@noreply.github.com>
Cc: Gürkan Erkilic <mail@erkilic.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Ax-LED/MMM-Navigate] run another module (#7)

 

@erkilic <https://github.com/erkilic> ,

can you tell me a link to your code on github?
From MMM-Navigate it is not possible to send instructions to your node_helper.js.
But you can complete the code of your main.js with code like https://github.com/Ax-LED/MMM-Navigate/blob/master/MMM-Navigate.js#L151.

Regards

AxLED
